settings: 
  commit_msg: "Update Andre601/README with new stats"
  max_lines: 10
  readme_file: "./TEMPLATE.md"
  url_text: "{REPO}{ID}"
  disabled_events:
  - 'comments'
  date:
    timezone: "Europe/Zurich"
    text: "Last update: `{DATE}`"
    format: "dd.mm.yyyy HH:MM:ss Z"
messages:
  comments: "{octicons/comment} **Commented:** {URL}"
  issue_opened: "{octicons/issueOpened} **Issue opened:** {URL}"
  issue_closed: "{octicons/issueClosed} **Issue closed:** {URL}"
  pr_opened: "{octicons/prOpened} **Pull request opened:** {URL}"
  pr_closed: "{octicons/prClosed} **Pull request closed:** {URL}"
  pr_merged: "{octicons/prMerged} **Pull request merged:** {URL}"
  create_repo: "{octicons/repo} **Created Repository:** {REPO}"
  changes_approved: "{octicons/approved} **Approved Changes:** {URL}"
  changes_requested: "{octicons/requestedChanges} **Requested Changes:** {URL}"
  new_release: "{octicons/release} **Created Release:** {URL}"
  new_star: "{octicons/star} **Starred** {REPO}"
  wiki_create: "{octicons/wiki} **Wiki Page created:** {WIKI} in {REPO}"
  fork_repo: "{octicons/forkedRepo} **Forked Repository:** {FORK} (From {REPO})"
